# ============================================================================
#  mk/rules.mk - derived variables + build / link / iso rules.
#  Included AFTER every module.mk so that SRCS is complete.
# ============================================================================

# --- Map sources to objects -------------------------------------------------
# src/<path>.c -> build/<path>.o   (pure text substitution, no wildcards)
OBJS := $(SRCS:$(SRC_DIR)/%=$(BUILD_DIR)/%)
OBJS := $(OBJS:.c=.o)
OBJS := $(OBJS:.s=.o)

# Header-dependency files generated by -MMD (one .d per object).
DEPS := $(OBJS:.o=.d)

# --- Compile C --------------------------------------------------------------
# mkdir -p $(dir $@) recreates the nested build/ path for this object.
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# --- Assemble boot code -----------------------------------------------------
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.s
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) -c $< -o $@

# --- Link the kernel binary -------------------------------------------------
$(KERNEL): $(OBJS)
	$(LD) $(LDFLAGS) $(OBJS) -o $@

# --- Build the bootable ISO -------------------------------------------------
$(ISO): $(KERNEL) $(GRUB_CFG)
	@command -v grub-mkrescue >/dev/null 2>&1 || { \
		echo "error: grub-mkrescue not found - run: sudo ./scripts/install-deps.sh"; exit 1; }
	@command -v xorriso >/dev/null 2>&1 || { \
		echo "error: xorriso not found - run: sudo ./scripts/install-deps.sh"; exit 1; }
	mkdir -p $(ISO_DIR)/boot/grub
	cp $(KERNEL) $(ISO_DIR)/boot/$(KERNEL)
	cp $(GRUB_CFG) $(ISO_DIR)/boot/grub/grub.cfg
	grub-mkrescue -o $(ISO) $(ISO_DIR) $(GRUB_FLAGS)

# --- Auto header dependencies -----------------------------------------------
# Pulls in build/**/*.d so editing a header rebuilds the right objects.
-include $(DEPS)
